AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'lib/open_gemdocs/mcp/tools.rb'

Metrics/ClassLength:
  Max: 350

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Layout/LineLength:
  Max: 200

Naming/AccessorMethodName:
  Exclude:
    - 'lib/open_gemdocs/mcp/tools.rb'

Style/MultilineBlockChain:
  Enabled: false
