#!/usr/bin/env ruby
# frozen_string_literal: true

require "uri"
require "net/http"
require "json"
require "optparse"
require_relative File.join("..", "lib", "open_gemdocs")

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: open-gem-docs [options] <gem_name>"

  opts.on("--local", "Use local documentation") do
    options[:local] = true
  end
  opts.on("-v", "--version VERSION", "Specify the version") do |version|
    options[:version] = version
  end

  opts.on("--latest", "Use the latest version") do
    options[:latest] = true
  end

  opts.on("-h", "--help", "Display this help message") do
    puts opts
    exit
  end

  opts.on("-s", "--stop", "stops the yard server") do
    OpenGemdocs::Yard.stop_server
    exit
  end
end.parse!

begin
  if options[:local]
    OpenGemdocs::Yard.browse_gem(ARGV[0])
  else
    OpenGemdocs::Browser.new(gem_name: ARGV[0], version: options[:version], use_latest: options[:latest]).open_browser
  end
rescue OpenGemdocs::Error, ArgumentError => e
  puts e.message
  exit 1
end
